services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    # environment:
    #   VAULT_DEV_ROOT_TOKEN_ID: root
    #   VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
    - ./.env.vault:/vault/vault-init:ro
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    networks:
      - transcendence-network
    healthcheck:
      test: ["CMD", "sh", "-c", "VAULT_ADDR=http://127.0.0.1:8200 vault status"]
      interval: 5s
      timeout: 3s
      retries: 5

  # vault-init:
  #   image: hashicorp/vault:1.15
  #   container_name: vault-init
  #   volumes:
  #     - vault-secrets:/run/secrets
  #     - ./.env.vault:/vault/vault-init:ro
  #     - ./vault/init.sh:/vault/init.sh:ro
  #   command: sh /vault/init.sh
  #   depends_on:
  #     vault:
  #       condition: service_healthy
  #   networks:
  #     - transcendence-network

  vault-agent:
    image: hashicorp/vault:1.15
    container_name: vault-agent
    environement:
      VAULT_ADDR: ${VAULT_ADDR}
    volumes:
      - ./vault/agent-config.hcl:/vault/agent/config.hcl:ro
      - ./vault/secrets:/vault/secrets
    command: vault agent -config=/vault/agent/config.hcl -foreground
    depends_on:
      vault:
        condition: service_healthy
    networks:
      - transcendence-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - ${DATA_PATH}/db_data:/var/lib/postgresql/data
      - vault-secrets:/run/secrets:ro
    depends_on:
      vault-init:
        condition: service_completed_successfully
    networks:
      - transcendence-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: node-backend
    environment:
      NODE_ENV: production
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_HOST: postgres
      DB_PORT: 5432
      VAULT_ADDR: http://vault:8200
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transcendence-network
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    environment:
      DOMAIN_NAME: ${DOMAIN}
    depends_on:
      - backend
    networks:
      - transcendence-network
    volumes:
      - ../secrets/certs:/etc/ssl/private/
    ports:
      - "5173:5173"
      

volumes:
  db_data:
    external: true
  site_data:
    external: true
  vault-secrets:

networks:
  transcendence-network:
    driver: bridge
