# ---- MODE ----
SecRuleEngine On

# ---- REQUETES ----
SecRequestBodyAccess On
SecRequestBodyLimit 10485760
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyLimitAction Reject

# ---- REPONSES ----
SecResponseBodyAccess On
SecResponseBodyLimit 524288
SecResponseBodyMimeType text/plain text/html application/json

# ---- LOGS ----
SecAuditEngine RelevantOnly
SecAuditLog /var/log/nginx/modsecurity_audit.log
SecAuditLogParts ABCFHZ
SecAuditLogType Serial

# ---- DONNEES TEMPORAIRES ----
SecTmpDir /tmp/modsecurity
SecDataDir /tmp/modsecurity

# ---- UPLOAD ----
SecUploadDir /tmp/modsecurity/upload
SecUploadKeepFiles Off

# ---- INCLURE OWASP CRS ----
Include /etc/nginx/modsecurity.d/owasp-crs/crs-setup.conf
Include /etc/nginx/modsecurity.d/owasp-crs/rules/*.conf