# Charge le module ModSecurity
load_module modules/ngx_http_modsecurity_module.so;

events
{
    worker_connections 1024;
}

http
{
    # ---- MODSECURITY ----
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsecurity.d/modsecurity.conf;

    # ---- MIME TYPES ----
    include /usr/local/nginx/conf/mime.types;
    default_type application/octet-stream;

    # ---- LOGS ----
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    # ---- SSL GLOBAL ----
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # ---- UPSTREAM ----
    upstream backend
    {
        server backend:3000;
    }

    # ---- REDIRECT HTTP TO HTTPS ----
    server
    {
        listen 80;
        server_name localhost;

        location / {
            return 301 https://$host:8081$request_uri;
        }
    }

    # ---- SERVER ----
    server 
    {
        listen 443 ssl;
        server_name localhost;
        
        # External certificat
        ssl_certificate /run/secrets/GameHub/certs/waf/waf.external.crt;
        ssl_certificate_key /run/secrets/GameHub/certs/waf/waf.external.key;
       
        # Internal certificat (to talk to frontend/backend)
        proxy_ssl_certificate /run/secrets/GameHub/certs/waf/waf.internal.crt;
        proxy_ssl_certificate_key /run/secrets/GameHub/certs/waf/waf.internal.key;
       
        # Verify internal certificat
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /run/secrets/GameHub/certs/waf/waf.internal.crt;
       
        # ---- HEADERS SECURITE ----
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
       
        # ---- FRONTEND (static files) ----
        location / {
            root /var/www/frontend;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # ---- BACKEND API ----
        location /api/ {
            proxy_pass https://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
       
        # ---- WEBSOCKET ----
        location /socket.io/ {
            proxy_pass https://backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}